name: "Deploy site"

on:

  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: "23 2 * * *"

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Lektor
        run: python -m pip install lektor

      - name: Build website
        run: lektor build -f webpack -O ./.build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build

