name: "Deploy site"

on:

  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
  workflow_dispatch:
    # Allow manually running workflow
  schedule:
    - cron: "23 2 * * *"

#env:
#  DEPLOY: >-
#    ${{
#    github.event_name != 'pull_request'
#    &&
#    github.ref == 'refs/heads/master'
#    }}
#  OUTPUT: _build

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
#      - uses: actions/setup-node@v3
#        with:
#          node-version: "lts/*"

      - name: Install Lektor
        run: python -m pip install lektor

      - name: Build website
        run: lektor build -f webpack -O ./.build
        #run: lektor build -f webpack -O '${{ env.OUTPUT }}'

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir ./.build
        #if: env.DEPLOY == 'true'
        #run: lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        #env:
        #  LEKTOR_DEPLOY_USERNAME: Tretyak0ff
        #  LEKTOR_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
